# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.0.1
  github-cli: circleci/github-cli@2.0.0


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  build_image_and_deploy:
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: "Get access token"
          command: |
            token=$( curl --location --request POST 'https://auth.astronomer.io/oauth/token' \
            --header 'content-type: application/json' \
            --data-raw '{ "client_id": "${{ secrets.ASTRONOMER_KEY_ID }}","client_secret": "${{ secrets.ASTRONOMER_KEY_SECRET }}","audience": "astronomer-ee","grant_type":"client_credentials"}' | jq -r '.access_token' )
            echo "::set-output name=auth_token::$token"
      - run:
          name: "Create image"
          command: |
            image=$( curl --location --request POST 'https://api.astronomer.io/hub/v1' \
            --header 'Authorization: Bearer ${{ steps.token.outputs.auth_token }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{"query":"mutation imageCreate(\n    $input: ImageCreateInput!\n) {\n    imageCreate (\n    input: $input\n) {\n    id\n    tag\n    repository\n    digest\n    env\n    labels\n    deploymentId\n  }\n}","variables":{"input":{"deploymentId":"${{ env.DEPLOYMENT_ID }}","tag":"deploy-${{ steps.date.outputs.date }}"}}}' | jq -r '.data.imageCreate.id')
            echo "::set-output name=image_id::$image"
      - run:
          name: "Deploy Image"
          command: |
            curl --location --request POST 'https://api.astronomer.io/hub/v1' \
            --header 'Authorization: Bearer ${{ steps.token.outputs.auth_token }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{"query":"mutation imageDeploy(\n    $input: ImageDeployInput!\n  ) {\n    imageDeploy(\n      input: $input\n    ) {\n      id\n      deploymentId\n      digest\n      env\n      labels\n      name\n      tag\n      repository\n    }\n}","variables":{"input":{"id":"${{ steps.image.outputs.image_id }}","tag":"deploy-${{ steps.date.outputs.date }}","repository":"images.astronomer.cloud/${{ env.ORGANIZATION_ID }}/${{ env.DEPLOYMENT_ID }}"}}}'


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2.1
  build-and-deploy-prod:
    jobs:
      - build_image_and_deploy:
          filters:
            branches:
              only:
                - main